# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0628249419547a4a942e4eb83ac203ab8054c47eba43bf09ed52d88c2f4f511552d4b5f130f33c5eafa6a8926e71b39afdaa79ef59105ce76b41ef3a39ec2e84

test:
  secret_key_base: c6b0ba4979e57168813fd68220282dfa9079eb8c0975efd3466c5616e46c8326fabcc8059eeaaf7bd34f9753f1f0398e12a6312f77c68ef66401620ac399ae99

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
